<pre class="text-left whitespace-pre-line xl:px-48">
I am a self-taught software developer and have been creating automation solutions for the charity telefundraising agency <a class="hyperlink" href="https://givetel.com/" target="_blank">Givetel</a> as an Operations Development Manager since 2021. I took on  this role after implementing some solutions to automate our internal reporting processes using VBA in 2020, saving hours of excel work per week that was being done by hand in the management team. This led to learning Python and developing these solutions further, increasing the spread of information that could be provided and the speed of the feedback loop our team had to work with.

As I continued and gained experience interacting with web API's, we reached a point where we needed to migrate calling platforms with some urgency created by a data breach that happened in our industry at the time. This meant we needed to rebuild our own API's from scratch, as our current setup was outsourced and the company that did it was not contactable. I utilized AWS API Gateway and Lambda functions to achieve this, along with setting up a MySQL database in AWS which would go on to serve many purposes.

Now that we had a new API, we needed a way to monitor its activity and export data that had been pushed to it. This gave me the opportunity to build an internal web platform Gecco (Givetel "Every Call Counts" Operations). I had been learning Typescript in my own time and it felt like a good change to apply that practically. I came across <a href="https://twitter.com/t3dotgg" target="_blank" class="hyperlink">Theo's</a> <a href="https://create.t3.gg/" target="_blank" class="hyperlink">T3 Stack</a> and the concepts were straightforward enough for me to build what we needed quite quickly.

Learning NextJS in combination with TRPC and Prisma made me appreciate some of the focuses of that stack, such as type-safety, composibility and creating types in the program that represented database schemas or queries to increase reliability. I found myself bringing patterns baxk to Python that I used more in the NextJS environment, particularly the use of types and callback functions.
</pre>
